version: '3.8'

services:
  wbo:
    image: lovasoa/wbo:latest
    restart: always
    labels:
          - "traefik.enable=true"
          - "traefik.http.routers.wbo.rule=Host(`paint.change.me`)"
          - "traefik.http.routers.wbo.entrypoints=websecure"
          - "traefik.http.routers.wbo.tls=true"
          - "traefik.http.services.wbo.loadbalancer.server.port=80"
          - "traefik.http.routers.wbo.tls.certresolver=myresolver"
    volumes:
      - wbo-boards:/opt/app/server-data
    networks:
      - proxy

volumes:
    wbo-boards:

networks:
  proxy:
    name: proxy