---
services:
  db:
    image: mariadb:11
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=forgejo
      - MYSQL_DATABASE=forgejo
      - MYSQL_USER=forgejo
      - MYSQL_PASSWORD=forgejo
      
  forgejo:
    image: codeberg.org/forgejo/forgejo:9.0
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - proxy
      - internal
    volumes:
      - ./forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.forgejo.rule=Host(`git.change.me`)"
      - "traefik.http.routers.forgejo.entrypoints=websecure"
      - "traefik.http.routers.forgejo.tls=true"
      - "traefik.http.routers.forgejo.tls.certresolver=myresolver"
      - "traefik.http.services.forgejo.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
    ports:
      - "2222:22"

volumes:
  db_data:

networks:
  proxy:
    name: proxy
  internal:
    driver: bridge